export const ADD_CART='ADD_CART';
export const TOGGLE_BUTTON='TOGGLE_BUTTON';
export const TOGGLE_BUTTON_CLOSE='TOGGLE_BUTTON_CLOSE';

export const REMOVE_BUTTON='REMOVE_BUTTON';

export const DESCRIBE='DESCRIBE';
 export const DESCRIBE_CLOSE='DESCRIBE_CLOSE';




 export const NEWW_ITEM_SET=" NEWW_ITEM_SET"